config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'pages#home'

    get "/about_us", to: "pages#about_us"
    get "/tarifs", to: "pages#tarifs"
    get "/casas", to: "pages#casas"

    resources :bookings, only: [:new, :edit, :update, :create]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  validates :last_name, :first_name, :email, :phone, :adults, :childrens, :arrival_date, :departure_date, :street, :city, :zipcode, :country, presence: true
  validates :adults, :childrens, inclusion: { in: (0..5).to_a}
  
  scope :pending, ->{where(state: :pending)}
  scope :deposit_requested, ->{where(state: :waiting_for_deposit)}
  scope :confirmed_and_paid, ->{where(state: :confirmed_and_paid)}
  scope :confirmed_waiting_for_payment, ->{where(state: :confirmed_waiting_for_payment)}
  scope :denied, ->{where(state: :denied)}
  scope :closed, ->{where(state: :closed)}
  scope :refund_pending, ->{where(state: :refund_pending)}
  scope :cancelled, ->{where(state: :cancelled)}
  scope :famille, ->{where(special_status: "Famille")}
  scope :clients, ->{where(special_status: "Aucun")}
  scope :maintenance, ->{where(special_status: "Maintenance")}

  STATE = ['pending', 'waiting_for_deposit', 'confirmed_waiting_for_payment', 'confirmed_and_paid' 'refund_pending', 'cancelled', 'denied', 'closed']
  SPECIAL = ['Aucun', 'Famille', 'Maintenance']
  CASAS = ['Savana', 'Bambu', 'Azulejos']

  # States: :pending, :waiting_for_deposit, :confirmed_waiting_for_payment, :refund_pending, :cancelled, :denied, :closed

  state_machine :state, initial: :pending do
  # When creating the booking --> mail
  # after_transition pending: :waiting_for_deposit, do: :send_mail # Mail App : (1) Mail to customer booking received, (2) Mail to owner new booking awaiting
  # after_transition waiting_for_deposit: :confirmed_waiting_for_payment, do: :send_confirmation_mail
  # after_transition waiting_for_deposit: :cancelled, do :send_cancelling_mail
  # after_transition pending: :denier, do :send_denial_mail

    event :requested_deposit do
      transition pending: :waiting_for_deposit
    end

    event :deny do
      transition pending: :denied
    end

    event :confirm_wait_for_payment do
      transition waiting_for_deposit: :confirmed_waiting_for_payment
    end

    event :confirm_and_paid do
      transition confirmed_waiting_for_payment: :confirmed_and_paid
    end

    event :close do
      transition confirmed_and_paid: :closed
    end

    event :refund_asked do
      transition confirmed_waiting_for_payment: :refund_pending
    end

    event :refund_asked do
      transition confirmed_and_paid: :refund_pending
    end

    event :cancel do
      transition [:waiting_for_deposit, :refund_pending] => :cancelled
    end


  end

  # after_initialize do
  #   @date_today = Date.today
  #   @date_today = @date_today.strftime("%Y-%m-%d")

  #     if @date_today > Booking.find(id=1)
  #       puts "coucou"
  #   end
  # end



end

app/models/casa.rb
class Casa < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale

  private

  def set_locale
    I18n.locale = extract_locale || locale_from_header || I18n.default_locale
  end

  def locale_from_header
    # The locale array is defined with symbols, so the first step is to change it to strings
    @available_locales_strings = I18n.available_locales.map do |language|
      language.to_s
    end
    # We initialize a variable result with the value false, so that we can return false if none of
    # languages from the header is included in the defined locales
    result = false
    # We go through each of the languages from the header and check if it is included in the locales
    # if it is included, we reassign the variable result to the language
    request.env.fetch('HTTP_ACCEPT_LANGUAGE', '').scan(/[a-z]{2}/).each do |language|
      if @available_locales_strings.include?(language)
        return result = language
      end
    end
    result
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : false
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @booking = Booking.new(booking_params)
    @booking.state = 'pending'
    if @booking.save
      sleep(3)
      BookingMailer.new_booking(@booking).deliver_now
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @booking = Booking.new
  end



  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(params[:booking])
    # Will raise ActiveModel::ForbiddenAttributesError
  end



  private

  def booking_params
    params.require(:booking).permit(:arrival_date, :departure_date, :first_name, :last_name, :email, :phone, :adults, :childrens, :baby_bed, :street, :city, :zipcode, :country, :state, :locale, :comment, :language, :special_status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def casas
  end

  def home
  end


  def about_us
  end

  def tarifs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= javascript_pack_tag 'people_limit' %>
<%= javascript_pack_tag 'booking_field_validation' %>
<!-- Tab links -->
<div class="container-fluid " style="object-fit:cover; width:100vw; height:100%; padding-left : 0; margin: 0; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path 'domaine.JPG' %>); background-size: cover">
  <div class="container-fluid" id="grad1">
    <div class="title-center d-flex justify-content-center" >
      <%= link_to root_path, class: "navbar-brand column-center" do%>
        <h1 class="font-text vivenda-size-big color-to-white"> <%= " Vivenda "%> </h1>
        <h2 class="font-text nossa-size-big color-to-white "> <%="- a Nossa Coroa -"%></h2>
      <% end %>
    </div>
    <div class="w-100 d-flex justify-content-center align-items-center align-self-end">
      <div class="new-session-form col-10 col-md-6 shadow p-3 mb-5 bg-white rounded d-flex flex-column justify-content-center">
        <h1 class="text-center pb-3 mb-0 op-7"><strong><%= t(".title") %></strong></h1>
        <div class="inputs-container-registration px-4">
          <%= simple_form_for [@booking] do |f| %>
            <div class="booking-calendar">
              <%= f.input :range_date, as: :string, input_html: {class: "datepicker-arrival pl-5", id: "arrival-date"}  %> </div>
            </div>
            <%= f.input :arrival_date, as: :string, :as => :hidden, input_html: {class: "datepicker-disable", id: "arrival-date-input"}  %>
            <%= f.input :departure_date, as: :string, :as => :hidden, input_html: {class: "datepicker-departure", id: "departure-date-input"} %>
            <div class="form-row px-4">
              <div class="form-group col-md-6">
                <%= f.input :adults, input_html: {id: "booking_adults"}, default: 0, collection: 0..5 %>
              </div>
              <div class="form-group col-md-6">
                <%= f.input :childrens, input_html: {id: "booking_children"}, default: 0, collection: 0..5 %>
              </div>
              <%= f.input :baby_bed, as: :boolean, boolean_style: :inline, input_html: {class: "label"} %>
            </div>
            <div class="form-row px-4">
              <div class="form-group col-md-6">
                <%= f.input :first_name %>
              </div>
              <div class="form-group col-md-6">
                <%= f.input :last_name %>
              </div>
            </div>
            <div class="form-row px-4">
              <div class="form-group col-md-6">
                <%= f.input :email %>
              </div>
              <div class="form-group col-md-6">
                <%= f.input :phone %>
              </div>
            </div>
            <div class="form-row px-4">
              <div class="form-group col-md-6">
                <%= f.input :street %>
              </div>
              <div class="form-group col-md-6">
                <%= f.input :city %>
              </div>
            </div>
            <div class="form-row px-4">
              <div class="form-group col-md-6">
                <%= f.input :zipcode %>
              </div>
              <div class="form-group col-md-6">
                <%= f.input :country %>
              </div>
            </div>
            <div class="form-row px-4">
              <%= f.input :comment, as: :text, :maxlength => 300  %>
            </div>
            <%= f.submit "#{t('.confirm')}", id:"booking-button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>               
                      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-164191375-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-164191375-1');
    </script>
    <title>Vivenda a Nossa Coroa</title>
    <meta name="description" content="Holiday rental of 3 furnished bungalows with a swimming pool, in the center of Portugal. The bungalows are surrounded by nature, giving a calm and relaxing atmosphere." />
    <meta property="og:title" content="Vivenda a Nossa Coroa - Holiday rentals with swimming pool">
    <meta property="og:description" content="Holiday rental of 3 furnished bungalows with a swimming pool, in the center of Portugal. The bungalows are surrounded by nature, giving a calm and relaxing atmosphere.">
    <meta property="og:image" content="https://scontent.fbru1-1.fna.fbcdn.net/v/t1.0-9/71590556_133607354681248_314461614034124800_o.jpg?_nc_cat=110&_nc_sid=cdbe9c&_nc_ohc=h8ImzizNdBkAX8SGio7&_nc_ht=scontent.fbru1-1.fna&oh=08464c0c4e98118e7ce49bff73a3a215&oe=5FB4E9C6">
    <meta property="og:url" content="https://www.anossacoroa.com">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'></script>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script src="sweetalert2.all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <%= favicon_link_tag %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer class="footer-border">
  <div class="row ">
    <div class="col-12 order-last col-md-9 order-md-first ">
      <p class="footer-font">
        info@anossacoroa.com <br>
        +32 477 24 57 26 <br>
        +351 915274823
      </p>
      <p class="adress footer-font">
        Vivenda a Nossa Coroa <br>
        Vale do Forno, <br>
        3305-183 Coja, Portugal <br>
      </p>
      <p class="footer-font">Alojamento local 119/AL <br>
      Palpiteximio LDA <br>
      NIF : 515884880 </p>
    </div>

    <div class="col-12 order-first col-md-3 order-md-last item icon footer-icons">
      <a href="tel:+32477245726" target="_blank"><i class="fas fa-phone icon-footer circle-icon" ></i></a>
      <a href="mailto:info@anossacoroa.com" target="_blank"><i class="far fa-envelope icon-footer circle-icon"></i></a>
      <a href="info@anossacoroa.com" target="_blank"></a>
      <a href="https://www.facebook.com/anossacoroa" target="_blank"> <i class="fab fa-facebook-f icon-footer circle-icon" ></i></a>
      <a href="https://www.instagram.com/vivendaanossacoroa/" target="_blank"><i class="fab fa-instagram icon-footer circle-icon"></i></a>
    </div>
  </div>
</footer>
<div class="reclamation">
  <a href="https://www.livroreclamacoes.pt/inicio" target="_blank"><%= image_tag('livro_de_reclamacoes.png')%></a>
</div>

app/views/pages/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light sticky navbar-white" id="navbar-container">
    <div class="container-nav">
      <div class="dropdown side-element">
        <button class="btn btn-secondary font-text drop-menu text-white " type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <img src="<%= image_path 'menuBarGreen.png' %>"  id="menu-btn-green" class="menu-bar" >
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <%= link_to root_path, class: "nav-item nav-link dropdown-item" do %>
          <%= t('global.navbar.home') %>
          <% end %>
          <%= link_to tarifs_path, class: "nav-item nav-link dropdown-item" do %>
          <%= t('global.navbar.rates') %>
          <% end %>
          <%= link_to casas_path, class: "nav-item nav-link dropdown-item" do %>
          <%= t('global.navbar.casas') %>
          <% end %>
          <%= link_to about_us_path, class: "nav-item nav-link dropdown-item" do %>
          <%= t('global.navbar.about_us') %>
          <% end %>
          <%= link_to new_booking_path, class: "nav-item nav-link dropdown-item" do %>
          <%= t('global.navbar.book') %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= link_to 'EN', url_for(locale: :en), class: "nav-item nav-link dropdown-item d-inline padding-drop", style:"padding: 0.5rem;"%>
          <%= link_to 'FR', url_for(locale: :fr), class: "nav-item nav-link dropdown-item d-inline padding-drop", style:"padding: 0.5rem;"%>
          <%# link_to 'PT', url_for(locale: :pt), class: "nav-item nav-link dropdown-item d-inline padding-drop", style:"padding: 0.5rem;"%>
          <%= link_to 'NL', url_for(locale: :nl), class: "nav-item nav-link dropdown-item d-inline padding-drop", style:"padding: 0.5rem;"%>
        </div>
      </div>

        <div class="title-center">
          <%= link_to root_path, class: "navbar-brand column-center" do  %>
            <h1 class="font-text color-to-green vivenda-size-small"> <%= " Vivenda " %> </h1>
            <h2 class="font-text color-to-green nossa-size-small "> <%="- a Nossa Coroa -"  %> </h2>
          <% end %>
        </div>

        <div class="side-element reservez">
          <%= link_to new_booking_path, class: "nav-item reserver" do  %>
            <h2 class="font-text btn-call reservez" id="deco-none"><%= t('global.navbar.book') %></h2>
          <% end %>
        </div>
    </div>
  </nav>

app/views/pages/about_us.html.erb
<!-- Navbar -->
<%= render "navbar"%>
<!-- about us content -->
<div class="container ">
  <div class="row   ">
    <div class="col-sm-12 col-lg-6 pt-5 pl-1">
      <%= image_tag 'geneetdidier.JPG', class:"card-img-about", alt:"#{t('.domain_alt')}"%>
    </div>
    <div class="col-sm-12 col-lg-6 pt-5">
      <h1 class="title_about"><%= t('.about_us')%></h1>
      <div class="underline"></div>
      <p><%= t('.about_us_description_html')%></p>
     </div>
  </div>
</div>
<div class="p-3"></div>

<!-- Footer -->
<%= render "footer" %>

app/views/pages/casas.html.erb
<%= render "navbar" %>

<div class="container">
  <h1 class="mt-5" style="font-size: 2rem !important;"><%= t('.casas') %></h1>
  <div class="underline mb-5"></div>
  <div class="row">
    <div class="icones-casas col-4 col-lg-2 d-flex flex-column  align-items-center">
      <div class="rounded-background d-flex flex-column align-items-center">
        <%= image_tag "icon1_oven.png"%>
        <p><%= t('.equipped') %></p>
      </div>
    </div>
    <div class="icones-casas col-4 col-lg-2 d-flex flex-column  align-items-center">
     <div class="rounded-background d-flex flex-column align-items-center">
        <%= image_tag "icon2.png"%>
        <p><%= t('.swimming_pool') %></p>
      </div>
    </div>
    <div class="icones-casas col-4 col-lg-2 d-flex flex-column  align-items-center">
      <div class="rounded-background d-flex flex-column align-items-center">
        <%= image_tag "icon3.png"%>
        <p><%= t('.garden') %></p>
      </div>
    </div>
    <div class="icones-casas col-4 col-lg-2 d-flex flex-column  align-items-center">
     <div class="rounded-background d-flex flex-column align-items-center">
        <%= image_tag "icon4.png"%>
        <p><%= t('.sun') %></p>
      </div>
    </div>
    <div class="icones-casas col-4 col-lg-2 d-flex flex-column  align-items-center">
     <div class="rounded-background d-flex flex-column align-items-center">
        <%= image_tag "icon5.png"%>
        <p><%= t('.wifi') %></p>
      </div>
    </div>
    <div class="icones-casas col-4 col-lg-2 d-flex flex-column  align-items-center">
      <div class="rounded-background d-flex flex-column align-items-center">
        <%= image_tag "icon6.png"%>
        <p><%= t('.countryside') %></p>
      </div>
    </div>
  </div>
  <div class="row justify-content-center mt-5" id="text-casas">
    <p style="text-align: center; font-weight: bolder; padding: 2vh 5vw"><%= t('.text-casas_html') %></p>
  </div>

  <div class="row container-casas-cards mt-5 justify-content-center">
    <div class="casa-card col-10 col-lg-3">
      <%= image_tag 'savana_card.JPG', class:"card-picture" %>
      <h3 class="title-casa">Casa Savana</h3>
    </div>

    <div class="casa-card col-10 col-lg-3">
      <%= image_tag 'bambu_card.JPG', class:"card-picture" %>
      <h3 class="title-casa">Casa Bambu</h3>
    </div>

    <div class="casa-card col-10 col-lg-3">
      <%= image_tag 'azulejos_card.JPG', class:"card-picture" %>
      <h3 class="title-casa">Casa Azulejos</h3>
    </div>
  </div>

  <div class="description-casas-h my-5">
    <h3><%= t('.same_equipment')%></h3>
    <p><%= t('.same_equipment_txt_html') %></p>
    <h3 class="mt-5"><%= t('.common_spaces')%></h3>
    <p><%= t('.common_spaces_txt_html') %></p>
  </div>
</div>
<div class="pb-3 mt-5">
  <%= render "footer" %>
</div>

app/views/pages/tarifs.html.erb
<!-- Navbar -->
<%= render "navbar"%>

<div class="container">
  <h1 class="mt-5" style="font-size: 2rem !important;"><%= t('.rates') %></h1>
  <div class="underline"></div>
    <div class="prices my-5">
      <table class="full-price-table">
        <tr>
          <th><h4 class="mt-3 "><%= t('.occupation') %></h4></th>
          <th><h3 class="mt-3"><%= t('.high_season') %></h3></th>
          <th><h3 class="mt-3"><%= t('.medium_season') %></h3></th>
          <th><h3 class="mt-3"><%= t('.low_season') %></h3></th>
        </tr>
        <tr>
          <td></td>
          <td class="period-td"><%= t('.period_high') %></td>
          <td class="period-td"><%= t('.period_medium') %></td>
          <td class="period-td"><%= t('.period_low') %></td>
        </tr>
        <tr class="prices-rows">
          <td><%= t('.one_two') %></td>
          <td class="prices-td"><span><%= t('.price_week_high_1_html') %></span><br>
          <%= t('.price_night_high_1_html') %></td>
          <td class="prices-td"><span><%= t('.price_week_medium_1_html') %></span><br>
          <%= t('.price_night_medium_1_html') %>
          </td>
          <td class="prices-td"><span><%= t('.price_week_low_1_html') %></span><br>
          <%= t('.price_night_low_1_html') %>
          </td>
        </tr>
        <tr class="prices-rows">
          <td><%= t('.three') %></td>
          <td class="prices-td"><span><%= t('.price_week_high_2_html') %></span><br>
          <%= t('.price_night_high_2_html') %></td>
          <td class="prices-td"><span><%= t('.price_week_medium_2_html') %></span><br>
          <%= t('.price_night_medium_2_html') %>
          </td>
          <td class="prices-td"><span><%= t('.price_week_low_2_html') %></span><br>
          <%= t('.price_night_low_2_html') %>
          </td>
        </tr>
        <tr class="prices-rows">
          <td><%= t('.four') %></td>
          <td class="prices-td"><span><%= t('.price_week_high_3_html') %></span><br>
          <%= t('.price_night_high_3_html') %></td>
          <td class="prices-td"><span><%= t('.price_week_medium_3_html') %></span><br>
          <%= t('.price_night_medium_3_html') %>
          </td>
          <td class="prices-td"><span><%= t('.price_week_low_3_html') %></span><br>
          <%= t('.price_night_low_3_html') %>
          </td>
        </tr>
      </table>

      <table class="phone-price-table">
        <tr>
          <th class="w-50"><h3 class="mt-3"><%= t('.high_season') %></h3></th>
        </tr>
        <tr>
          <td class="period-td"><%= t('.period_high') %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= t('.one_two') %></td>
          <td class="prices-td"><span><%= t('.price_week_high_1_html') %></span><br>
          <%= t('.price_night_high_1_html') %></td>
        </tr>
        <tr>
          <td><%= t('.three') %></td>
          <td class="prices-td"><span><%= t('.price_week_high_2_html') %></span><br>
          <%= t('.price_night_high_2_html') %></td>
        </tr>
        <tr>
          <td><%= t('.four') %></td>
          <td class="prices-td"><span><%= t('.price_week_high_3_html') %></span><br>
          <%= t('.price_night_high_3_html') %></td>
        </tr>
      </table>
      <table class="phone-price-table">
        <tr>
          <th class="w-50"><h3 class="mt-3"><%= t('.medium_season') %></h3></th>
        </tr>
        <tr>
          <td class="period-td"><%= t('.period_medium') %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= t('.one_two') %></td>
          <td class="prices-td"><span><%= t('.price_week_medium_1_html') %></span><br>
          <%= t('.price_night_medium_1_html') %></td>
        </tr>
        <tr>
          <td><%= t('.three') %></td>
          <td class="prices-td"><span><%= t('.price_week_medium_2_html') %></span><br>
          <%= t('.price_night_medium_2_html') %></td>
        </tr>
        <tr>
          <td><%= t('.four') %></td>
          <td class="prices-td"><span><%= t('.price_week_medium_3_html') %></span><br>
          <%= t('.price_night_medium_3_html') %></td>
        </tr>
      </table>
      <table class="phone-price-table">
        <tr>
          <th class="w-50"><h3 class="mt-3"><%= t('.low_season') %></h3></th>
        </tr>
        <tr>
          <td class="period-td"><%= t('.period_low') %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= t('.one_two') %></td>
          <td class="prices-td"><span><%= t('.price_week_low_1_html') %></span><br>
          <%= t('.price_night_low_1_html') %></td>
        </tr>
        <tr>
          <td><%= t('.three') %></td>
          <td class="prices-td"><span><%= t('.price_week_low_2_html') %></span><br>
          <%= t('.price_night_low_2_html') %></td>
        </tr>
        <tr>
          <td><%= t('.four') %></td>
          <td class="prices-td"><span><%= t('.price_week_low_3_html') %></span><br>
          <%= t('.price_night_low_3_html') %></td>
        </tr>
      </table>
      <p class="mt-3"><%= t('.additional_info_occupation_html')%></p>
      <p class="mt-3"><%= t('.additional_info_1_html')%></p>
      <h2 class="mt-5"><%= t('.long_stays') %></h2>
      <div class="underline"></div>
        <div class="row border-tarif">
          <div class="col-4">
            <h3><%= t('.low_season') %></h3>
            <p><%= t('.period_low') %></p>
            <p class="prices-table"><%= t('.price_month_low_html') %></p>
          </div>
          <div class="col-4">
            <h3><%= t('.medium_season') %></h3>
            <p class="prices-table"><%= t('.period_medium') %></p>
            <p class="prices-table"><%= t('.price_month_medium_html') %></p>
          </div>
        </div>
        <p class="mt-3"><%= t('.additional_info_2_html')%></p>

      <h2 class="mt-5"><%= t('.details') %></h2>
      <div class="underline"></div>
      <div class="row justify-content-center mt-1">
        <p class="col-12 mt-1">
          <%= t('.payment_html') %>
        </p>
      </div>
    </div>
  </div>
​</div>
​
<!-- Footer -->
<%= render "footer"%>